import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

// Create a Title component that'll render an <h1> tag with some styles
const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;

// Create a Wrapper component that'll render a <section> tag with some styles
const Wrapper = styled.section`
  padding: 4em;
  background: papayawhip;
`;

// Use Title and Wrapper like any other React component – except they're styled!

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alis Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Alis Learning</h1>

      <Wrapper>
        <Title>Hello World!</Title>
      </Wrapper>
    </div>
  );
}
